version: 2.1
orbs:
  node: circleci/node@4.0.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    working_directory: ~/ShopifyWinter2021/backend
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - node/install-packages:
          cache-path: ~/ShopifyWinter2021/node_modules
          override-ci-command: npm install
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: shc2021
          tag: "v1"
      - gcr/push-image:
          image: shc2021
          tag: "v1"
workflows:
  build_update_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - Build-Push-Image-Docker:
          requires:
            - build
          filters:
            branches:
              only: dev