version: 2.1
orbs:
  node: circleci/node@1.0.1
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    description: Install npm
    machine: true
    steps:
      - checkout
      - run:
          name: Move
          command: cd backend
      - node/install
      - node/install-npm
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: npm install
          cache-key: package.json
          use-strict-cache: true
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: circle-gke
          tag: "v1"
      - gcr/push-image:
          image: circle-gke
          tag: "v1"
workflows:
  build_update_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - Build-Push-Image-Docker:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy:
          requires:
            - Build-Push-Image-Docker
          filters:
            branches:
              only: dev