version: 2.1
orbs:
  node: circleci/node@4.0.0
  gcr: circleci/gcp-gcr@0.0.2
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - node/install-packages:
          override-ci-command: npm install
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - gcr/gcr-auth
      - run:
          name: Get env vars
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV
            echo ${GCLOUD_SERVICE_KEY} > $HOME/shckeys.json
            docker build -t us.gcr.io/$GOOGLE_PROJECT_ID/shc2021 -t us.gcr.io/$GOOGLE_PROJECT_ID/shc2021:v1 .
      - gcr/push-image:
          image: shc2021
          tag: "v1"
workflows:
  build_update_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
      - Build-Push-Image-Docker:
          requires:
            - build
          filters:
            branches:
              only: dev