apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shc2021
  labels:
    app: shc2021
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shc2021
  template:
    metadata:
      labels:
        app: shc2021
    spec:
      containers:
        - image: us.gcr.io/shopifychallenge-288608/shc2021
          name: shc2021
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP